# Generated by Django 3.2.3 on 2022-01-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.CharField(default='', max_length=50),
        ),
    ]
